---

- homebrew:
    name: fish
- lineinfile:
    dest: /etc/shells
    line: /usr/local/bin/fish
  become: yes
- command: "chsh -s /usr/local/bin/fish {{ ansible_env.USER }}"
  become: yes

- command: curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
- shell: /usr/local/bin/fish -c "fisher add oh-my-fish/plugin-peco"
- shell: /usr/local/bin/fish -c "fisher add decors/fish-ghq"
- copy:
    src: "{{ item }}"
    dest: ~/.config/fish/conf.d/
  loop:
    - ghq.fish
    - peco.fish

- shell: curl -L https://get.oh-my.fish | fish
- shell: /usr/local/bin/fish -c "omf install bobthefish"
