- name: setup user environments
  hosts: localhost
  connection: local
  gather_facts: true

  roles:
    - { role: roles/system, sudo: yes }
    - { role: roles/homebrew }
    - { role: roles/zsh }
    - { role: roles/ssh }
    - { role: roles/git }
    - { role: roles/vagrant }
    - { role: roles/php53 }
    - { role: roles/python, sudo: yes }
    - { role: roles/ruby, version: 1.9.3-p547 }
    - { role: roles/go }