- name: setup user environments
  hosts: localhost
  connection: local
  gather_facts: true

  roles:
    - { role: roles/homebrew }
    - { role: roles/dotfiles }
    - { role: roles/zsh }
    - { role: roles/git, sudo: yes }
    - { role: roles/php53 }
    - { role: roles/python, sudo: yes }
    - { role: roles/ruby, version: 2.1.2 }