- name: setup user environments
  hosts: localhost
  connection: local
  gather_facts: true

  roles:
    - { role: roles/system }
    - { role: roles/homebrew }
    - { role: roles/ssh }
    - { role: roles/git }
    - { role: roles/zsh }
    - { role: roles/vim }
    - { role: roles/vagrant }
