- name: setup user environments
  hosts: localhost
  connection: local
  gather_facts: true

  roles:
    - { role: roles/system }
    - { role: roles/homebrew }
    - { role: roles/zsh }
    - { role: roles/ssh }
    - { role: roles/git }
    - { role: roles/vim }
    - { role: roles/vagrant }
    - { role: roles/python }
    - { role: roles/php70 }
    - { role: roles/ruby, version: 2.2.2 }
    - { role: roles/go }
