---

- name: ssh | mkdir conf.d
  file: path=~/.ssh/conf.d state=directory

- name: ssh | place .ssh/config
  copy: src=config dest=~/.ssh/conf.d/config

- name: ssh | assemble fragments
  assemble: src=~/.ssh/conf.d dest=~/.ssh/config mode=0600