---

- name: git | install git, hub, tig
  homebrew:
    name:
      - ghq
      - git
      - github/gh/gh
      - tig

- name: git | place .gitconfig
  copy: src=gitconfig dest=~/.gitconfig

- name: git | dir for templates
  file: path=~/.git_template/hooks state=directory

- name: git | place hook scripts
  copy: src={{ item }} dest=~/.git_template/hooks mode=0755
  with_items:
    - ctags
    - post-checkout
    - post-commit
    - post-merge
    - post-rewrite

- file: path=~/bin state=directory
- copy: src=git-delete-merged-branches dest=~/bin mode=0755

- name: git | configure credential.helper osxkeychain
  command: git config --global credential.helper osxkeychain

- command: git config --global ghq.root ~/src
