---
- name: git | install git, hub, tig
  homebrew: "name={{ item }}"
  with_items:
    - git
    - hub
    - tig

- name: git | download git-credential-osxkeychain
  get_url: url=https://github-media-downloads.s3.amazonaws.com/osx/git-credential-osxkeychain dest=/usr/local/bin

- name: git | add +x permission
  command: chmod u+x /usr/local/bin/git-credential-osxkeychain

- name: git | configure credential.helper osxkeychain
  command: git config --global credential.helper osxkeychain

- name: git | path to git
  command: brew --prefix git
  register: path_to_git

- name: git | link diff-highlight into PATH
  file: "src={{ path_to_git.stdout }}/share/git-core/contrib/diff-highlight/diff-highlight dest=/usr/local/bin/diff-highlight state=link"