---

- name: php | tap repositry
  command: "brew tap {{ item }}"
  with_items:
    - homebrew/php

- name: php | install
  homebrew: name="{{ item }}"
  with_items:
    - php70
    - composer

- include: psysh.yml
