---

- name: brew | update
  homebrew: update_homebrew=yes upgrade_all=yes

- name: brew | tap repositries
  homebrew_tap: "tap={{ item }}"
  ignore_errors: True
  with_items:
    - homebrew/versions
    - caskroom/cask

- name: brew | install packages
  homebrew: "name={{ item }}"
  with_items:
    - awscli
    - brew-cask
    - curl
    - mobile-shell
    - ngrep
    - pup
    - pwgen
    - the_silver_searcher
    - tmux
    - wget

- name: brew | install apps
  homebrew_cask: "name={{ item }}"
  with_items:
    - alfred
    - dash
    - dropbox
    - evernote
    - google-chrome
    - google-japanese-ime
    - hoster
    - itsycal
    - iterm2
    - karabiner
    - libreoffice
#    - onepassword
    - qlmarkdown
    - slack
#    - sophos-anti-virus-home-edition
    - sublime-text
    - sqwiggle
    - trailer
    - virtualbox

- include: ricty.yml
- include: jo.yml
