---

- name: brew | update
  homebrew: update_homebrew=yes upgrade_all=yes

- name: brew | tap repositries
  homebrew_tap: "tap={{ item }}"
  ignore_errors: True
  with_items:
    - aws/tap
    - homebrew/versions
    - caskroom/cask

- name: brew | install packages
  homebrew:
    name:
      - awscli
      - aws-sam-cli
      - curl
      - jo
      - jq
      - ngrep
      - pt
      - pup
      - tmux
      - wget

- name: brew | install apps
  homebrew_cask: "name={{ item }}"
  with_items:
    - dash
    - itsycal
    - iterm2
    - libreoffice
    - quitter
    - slack
    - trailer
    - virtualbox
    - visual-studio-code

- include: ricty.yml
