---

- name: brew | update
  homebrew: update_homebrew=yes upgrade_all=yes

- name: brew | tap repositries
  homebrew_tap: "tap={{ item }}"
  ignore_errors: True
  with_items:
    - homebrew/binary
    - homebrew/versions
    - caskroom/cask

- name: brew | install packages
  homebrew: "name={{ item }}"
  with_items:
    - awscli
    - ctags
    - curl
    - jo
    - jq
    - mobile-shell
    - ngrep
    - pt
    - pup
    - pwgen
    - tmux
    - wget

- name: brew | install apps
  homebrew_cask: "name={{ item }}"
  with_items:
    - dash
#    - hoster
    - itsycal
    - iterm2
    - libreoffice
    - qlmarkdown
    - quitter
    - slack
    - trailer
    - virtualbox
    - visual-studio-code

- include: ricty.yml
