---

- name: brew | update
  homebrew: update_homebrew=yes upgrade_all=yes

- name: brew | tap repositries
  homebrew_tap: "tap={{ item }}"
  ignore_errors: True
  with_items:
    - homebrew/versions
    - caskroom/cask

- name: brew | install packages
  homebrew: "name={{ item }}"
  with_items:
    - brew-cask
    - curl
    - mobile-shell
    - ngrep
    - pwgen
    - the_silver_searcher
    - wget

- name: brew | install apps
  homebrew_cask: "name={{ item }}"
  with_items:
    - alfred
    - coteditor
    - dash
    - dropbox
    - evernote
    - karabiner
    - google-chrome
    - google-japanese-ime
    - hoster
    - iterm2
    - libreoffice
    - mysqlworkbench
    - onepassword
    - qlmarkdown
    - skype
    - slack
    - sophos-anti-virus-home-edition
    - sublime-text
    - sqwiggle
    - virtualbox
    - yorufukurou

- name: brew | link alfred
  sudo: yes
  command: brew cask alfred link
