---

- homebrew: update_homebrew=yes upgrade_all=yes

- homebrew_tap: "tap={{ item }}"
  ignore_errors: True
  with_items:
    - aws/tap

- name: brew | install packages
  homebrew:
    name:
      - awscli
      - curl
      - jq
      - peco
      - pt
      - yarn
      - wget

- name: brew | install apps
  homebrew_cask: "name={{ item }}"
  ignore_errors: True
  with_items:
    - dash
    - itsycal
    - iterm2
    - quitter
    - slack
    - trailer
    - visual-studio-code

- include: ricty.yml
