---

- name: brew | update
  homebrew: update_homebrew=yes

- name: brew | tap repositries
  homebrew_tap: "tap={{ item }}"
  ignore_errors: True
  with_items:
    - homebrew/versions
    - caskroom/cask

- name: brew | install packages
  homebrew: "name={{ item }}"
  with_items:
    - wget
    - curl
    - mobile-shell
    - the_silver_searcher
    - pwgen
    - brew-cask

- name: brew | install apps
  homebrew_cask: "name={{ item }}"
  with_items:
    - alfred
    - coteditor
    - evernote
    - google-chrome
    - google-japanese-ime
    - hipchat
    - hoster
    - iterm2
    - kobito
    - libreoffice
    - mysqlworkbench
    - skype
    - slack
    - sophos-anti-virus-home-edition
    - sublime-text
    - virtualbox
    - yorufukurou

- name: brew | link alfred
  command: brew cask alfred link
