---
- homebrew: update_homebrew=yes upgrade_all=yes

- name: brew | install packages
  homebrew:
    name:
      - awscli
      - colordiff
      - coreutils
      - curl
      - grep
      - jq
      - pkg-config
      - peco
      - pt
      - pwgen
      - wget

- name: brew | install apps
  homebrew_cask: "name={{ item }}"
  ignore_errors: True
  with_items:
    - dash
    - itsycal
    - iterm2
    - quitter
    - slack
    - trailer
    - visual-studio-code
