---

- pip: name=neovim executable=~/.pyenv/shims/pip3
- homebrew: name=neovim/neovim/neovim
- git: repo=https://github.com/massat/.vim.git dest=~/.vim force=yes
- file: path=~/.config/nvim src=~/.vim state=link
- file: path=~/.config/nvim/init.vim src=~/.vim/.vimrc state=link

- include: dein.yml
