---

- homebrew: name=neovim/neovim/neovim
- git: repo=git@github.com:massat/.vim.git dest=~/.vim force=yes
- file: path=~/.config/nvim src=~/.vim state=link
- file: path=~/.config/nvim/init.vim src=~/.vim/.vimrc state=link

- include: python3.yml
- include: dein.yml
