---

- name: ruby | update profile
  lineinfile: dest=~/.myzshrc line='eval "$(rbenv init -)"'

- name: ruby | place .gemrc
  template: "src=gemrc dest=~/.gemrc"

- name: ruby | install bundler
  gem:  name={{ item }}
  with_items:
    - bundler
    - git-pr-release
    - neovim
    - pry
    - refe2
    - rsense
    - rubocop
    # requirements of vscode's ruby extension
    - rcodetools
